-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM((SALES * PRICE)) AS TOTAL_SALES
FROM AUTHOR A
INNER JOIN BOOK B ON A.AUTHOR_ID = B.AUTHOR_ID
INNER JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE TO_CHAR(S.SALES_DATE, 'YYYYMM') = '202201'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC


/*
1. AUTHOR 테이블과 BOOK 테이블을 AUTHOR_ID 기준으로 INNER JOIN, BOOK_SALES 테이블과 BOOK_ID 기준으로 INNER JOIN
2. SALES_DATE를 YYYYMM로 형변환해 출력
3. SELECT 문에 판매가 * 판매량의 SUM을 구함

*/
