-- 코드를 입력하세요
SELECT A.CAR_ID, A.CAR_TYPE, (100-DISCOUNT_RATE)*(30*DAILY_FEE)/100 AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
ON A.CAR_TYPE = B.CAR_TYPE
WHERE A.CAR_TYPE IN ('세단', 'SUV')
AND A.CAR_ID NOT IN (
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(START_DATE,'YYYYMMDD') <= '20221130' AND TO_CHAR(END_DATE,'YYYYMMDD') >= '20221101')
AND B.DURATION_TYPE = '30일 이상'
AND (100-DISCOUNT_RATE)*(30*DAILY_FEE)/100 BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
