-- 코드를 입력하세요
SELECT CAR_ID, ROUND(AVG(END_DATE - START_DATE + 1),1) AS AVERAGE_DURATION 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING ROUND(AVG(END_DATE - START_DATE + 1),1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC


/* #오답노트
HAVING AVERAGE_DURATION >= 7 -> 오류 발생
SQL 실행 순서로 인하여 
FROM - WHERE - GROUP BY - HAVING - SELECT - ORDER BY 순으로 진행되므로 SELECT절에서 선언한 평균 대여 기간을 HAVING절에서 사용할 수 없음
*/