-- 코드를 입력하세요
SELECT TO_CHAR(SALES_DATE,'YYYY') AS YEAR
, TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) AS MONTH -- TO_CHAR --> 03, TO_NUMBER -> 3
, COUNT(DISTINCT(USER_ID)) AS PURCHASED_USERS
, ROUND(COUNT(DISTINCT(USER_ID)) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE TO_CHAR(JOINED,'YYYY') = '2021'), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID FROM USER_INFO WHERE TO_CHAR(JOINED,'YYYY') = '2021')
GROUP BY TO_CHAR(SALES_DATE,'YYYY'), TO_CHAR(SALES_DATE,'MM')
ORDER BY YEAR ASC, MONTH ASC







-- 신한카드 코딩테스트 유사문제 출제 