-- 코드를 입력하세요
SELECT T.FLAVOR
FROM (
    SELECT FH.FLAVOR, SUM(FH.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) AS TOTAL
FROM FIRST_HALF FH
INNER JOIN JULY J ON FH.FLAVOR = J.FLAVOR
GROUP BY FH.FLAVOR
ORDER BY TOTAL DESC) T
WHERE ROWNUM <= 3
/*
FIRST_HALF 테이블과 JULY XPDLQMFDMF FLAVOR 기준으로 INNER JOIN 하고, FLAVOR로 GROUP BY 해서 각 테이블의 TOTAL_ORDER를 SUM 해서 출력
*/
