-- 코드를 입력하세요
SELECT AP.APNT_NO, P.PT_NAME, P.PT_NO, AP.MCDP_CD, D.DR_NAME, AP.APNT_YMD
FROM APPOINTMENT AP
INNER JOIN PATIENT P ON AP.PT_NO = P.PT_NO
INNER JOIN DOCTOR D ON AP.MDDR_ID = D.DR_ID
WHERE TO_CHAR(AP.APNT_YMD,'YYYYMMDD') = '20220413'
AND AP.APNT_CNCL_YN = 'N'
AND D.MCDP_CD = 'CS'
ORDER BY APNT_YMD ASC